version: '3.8'

services:
  ledger-portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: gl-core-ledger-portal:latest
    container_name: gl-core-ledger-portal
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Uncomment if you need to mount configuration files
    # volumes:
    #   - ./config:/usr/share/nginx/html/assets/config
    networks:
      - gl-core-network

  # Uncomment if you have a backend API service
  # backend-api:
  #   image: your-backend-api:latest
  #   container_name: tata-backend-api
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=your-database-connection-string
  #   networks:
  #     - gl-core-network

networks:
  gl-core-network:
    driver: bridge
